# build Configuration, i.e. Debug, Release, etc.
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# scripts to run before build
before_build:
  - dotnet restore

build_script:
  - dotnet build .\SnmpSharpNet.sln

# test_script:
#   - dotnet test .\VtNetCore.Unit.Tests\

artifacts:
  - path: SnmpSharpNet\bin\Release\*.nupkg
  
deploy:
- provider: NuGet
  api_key:
    secure: YKZaqdwfOUXaFvViKr0R3C0GGIscZQ/3NU9OUv6YJnY=